import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import getIcons from '../components/socialIcons'

const Home: NextPage = () => {
  const [drawerState, setDrawer] = useState(false);
  const [drawerStyle, setStyle] = useState({display: 'none'});

  const handleDrawer = () => {
    setDrawer((state) => !(state));
    if(drawerState){
      setStyle({display: 'none'});
    }else{
      setStyle({display: 'flex'});
    }
    console.log(drawerStyle)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Hank Berger | Front-end Developer</title>
        <meta name="description" content="Frontend developer and artist. Focused on delivering quality engineering alongside great design." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img className={styles.background} src='Website.png' alt="Art generated by Artificial Intelligence and Hank Berger."/>
        <nav id="home"className={styles.navbar}>
          <a className={styles.logocontainer} href='/'>
           <img className={styles.logo} src='/hankicon.webp' alt="Hank Berger's Logo"/>
          </a>
          <div className={styles.linkcontainer}>
              <a href='#home'>
                Home
              </a>
              <a href='#about'>
                About
              </a>
              <a href='#experience'>
                Experience
              </a>
              <a href='#gallery'>
                Gallery
              </a>
              <a href='#contact'>
                Contact
              </a>
          </div>
          <div onClick={handleDrawer} className={styles.hamburger}>
              <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" className="bi bi-list" viewBox="0 0 16 16">
                <path fillRule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
              </svg>
          </div>
          <div className={styles.drawerContainer} onClick={handleDrawer} style={drawerStyle}>
            <div className={styles.drawer} >
              <svg onClick={handleDrawer} xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" className="bi bi-x-lg" viewBox="0 0 16 16">
                <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
              </svg>
              <img src="/icondark.png" alt="Hank Berger logo"/>
              <a href='#home'>
                Home
              </a>
              <a href='#about'>
                About
              </a>
              <a href='#experience'>
                Experience
              </a>
              <a href='#gallery'>
                Gallery
              </a>
              <a href='#contact'>
                Contact
              </a>
            </div>
          </div>
        </nav>
        <div className={styles.splash}>
          <div className={styles.title}>
            <h1>Hank Berger</h1>
            <p>Front-end Developer and Artist.</p>
          </div>
        </div>
        <div id="about" className={styles.about}>
          <div className={styles.aboutcontent}>
            <h1>About</h1>
            <img draggable='false' src="/hankberger.webp" alt="A professional headshot of Hank Berger."/>
            <a href='https://drive.google.com/file/d/1AHmQBI_zATwpxUFLofD9318Q30n2dTCS/view?usp=sharing' target='_blank'>resume</a>
            <p>Hi! I'm Hank, a front-end developer and digital artist interested in working with the cutting edge of technology and art.</p>
            <p>My technical skills include React, TypeScript, NodeJS, SASS (CSS), and SQL. As an artist, my main focus is in 3D animation and AI art. I am well versed in Cinema4D, Adobe After Effects, Photoshop, Illustrator, and Premiere.</p>
            {/* <p>I'm a recent computer science graduate from the University of Minnesota, if you want to learn more about me you can find my resume here. Feel free to get in contact with me through the form below.</p> */}
          </div>
        </div>
        <div id='experience' className={styles.experience}>
          <div className={styles.experienceContent}>
            <h1>Experience</h1>
            <div className={styles.expContainer}>
              <div className={styles.expGrid} style={{marginTop: '0px'}}>
                <div className={styles.expTitle}>
                  <h4>
                    May 2022 - Present
                  </h4>
                  <h2>
                    Ameriprise Financial
                  </h2>
                  <h3>
                    Technology Intern
                  </h3>
                </div>
                <div className={styles.expDesc}>
                  <p>Intern on the Digital Platform Engineering Team. My main tasks included creating a dynamic React app by pulling content from our headless CMS, Watson Discovery Search Integration using a NodeJS server, and release management support using CI/CD tools such as Jenkins, Git, and AWS.</p>
                </div>
              </div>
              <div className={styles.expGrid}>
                <div className={styles.expTitle}>
                  <h4>
                    May 2021 - May 2022
                  </h4>
                  <h2>
                    CT Holdings
                  </h2>
                  <h3>
                    Software Developer Intern
                  </h3>
                </div>
                <div className={styles.expDesc}>
                  <p>Full stack application development using the MERN (MariaDB, Express, React, NodeJS) stack. Business automation scripts using Python. Meeting with clients to develop technology solutions to their problems.</p>
                </div>
              </div>
              <div className={styles.expGrid}>
                <div className={styles.expTitle}>
                  <h4>
                    January 2021 - October 2021
                  </h4>
                  <h2>
                    University of Minnesota
                  </h2>
                  <h3>
                    Research Assistant
                  </h3>
                </div>
                <div className={styles.expDesc}>
                  <p>Research Assistant for Digital Arts, Sciences, and Humanities (DASH). The main goal was to assist humanities researchers utilize technology in their research. Main tasks included data visulization using Python and website development for research teams.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id='gallery' className={styles.gallery}>
          <div className={styles.galleryContent}>
              <h1>Gallery</h1>
              <div className={styles.galleryGrid}>
                <div className={styles.art}>
                  <video src="/hairdance2.mp4" muted autoPlay loop/>
                  <div className={styles.cover}>
                    <h2>3D Art</h2>
                  </div>
                </div>
                <div className={styles.aiart}>
                <video src="/ai.mp4" muted autoPlay loop/>
                  <div className={styles.cover}>
                    <h2>AI Art</h2>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <div id='contact' className={styles.contact}>
          <div className={styles.contactContent}>
            <h1>Contact Me</h1>
            <div className={styles.socialIcons}>
              {getIcons().map((icon:{name: string, link: string, html: string}, i: number)=>{
                return(
                <a href={icon.link}>
                  <div key={i} className={styles.icon} dangerouslySetInnerHTML={{__html: icon.html}}>
                    
                  </div>
                </a>
                )
              })}
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}

export default Home
